#digite 20 numeros#

n1=float(input("digite um numero"))
n2=float(input("digite um numero"))
n3=float(input("digite um numero"))
n4=float(input("digite um numero"))
n5=float(input("digite um numero"))
n6=float(input("digite um numero"))
n7=float(input("digite um numero"))
n8=float(input("digite um numero"))
n9=float(input("digite um numero"))
n10=float(input("digite um numero"))
n11=float(input("digite um numero"))
n12=float(input("digite um numero"))
n13=float(input("digite um numero"))
n14=float(input("digite um numero"))
n15=float(input("digite um numero"))
n16=float(input("digite um numero"))
n17=float(input("digite um numero"))
n18=float(input("digite um numero"))
n19=float(input("digite um numero"))
n20=float(input("digite um numero"))
print("")
n=n1+n2+n3+n4+n5+n6+n7+n8+n9+n10+n11+n12+n13+n14+n15+n16+n17+n18+n19+n20
l=n1,n2,n3,n4,n5,n6,n7,n8,n9,n10,n11,n12,n13,n14,n15,n16,n17,n18,n19,n20
print("Soma dos números",n)
m=n/20
print("Média dos números",m)
print("Número menor", min(l))
print("Numero maior",max(l))
